// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqMSDEXEjZa3QYs1hReRLhpA5mfPAfqGg',
    appId: '1:98767185642:web:76ede13f84c14f41a89993',
    messagingSenderId: '98767185642',
    projectId: 'chatconnect-b5073',
    authDomain: 'chatconnect-b5073.firebaseapp.com',
    storageBucket: 'chatconnect-b5073.firebasestorage.app',
    measurementId: 'G-TW8GDQ4VVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfkEbwdptcPmlTJLDHhemYO2Yweza6l6w',
    appId: '1:98767185642:android:de560678d0cde974a89993',
    messagingSenderId: '98767185642',
    projectId: 'chatconnect-b5073',
    storageBucket: 'chatconnect-b5073.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf6iAa1-dqaNbcJbjes_Y3agYQg62p0Lc',
    appId: '1:98767185642:ios:67bea2b2360cac98a89993',
    messagingSenderId: '98767185642',
    projectId: 'chatconnect-b5073',
    storageBucket: 'chatconnect-b5073.firebasestorage.app',
    iosBundleId: 'com.overtidea.chatconnect',
  );
}
